pub const FRACTURED: &str = "FracturedItem True";
pub const INFLUENCED: &str = "HasInfluence Crusader Elder Hunter Redeemer Shaper Warlord";
pub const SYNTHESIZED: &str = "SynthesisedItem True";
pub const ENCHANTED: &str = "AnyEnchantment True";
pub const VEILED: &str = "\"Veil\"";
pub const REPLICA: &str = "Replica True";
pub const TIER_ONE_MODS: [&str; 98] = [
    "Abating",
    "Apparition's",
    "Archmage's",
    "Behemoth's",
    "Blazing",
    "Champion's",
    "Cheetah's",
    "Cherub's",
    "Countess's",
    "Devastating",
    "Dictator's",
    "Discharging",
    "Duchess's",
    "Elevated ",
    "Elevated",
    "Emperor's",
    "Empress's",
    "Esh's",
    "Essences",
    "Exalter's",
    "Fawn's",
    "Frost Singer's",
    "Ghost's",
    "Glyphic",
    "Guatelitzi's",
    "Hellion's",
    "Hero's",
    "Impenetrable",
    "Impervious",
    "Incandescent",
    "Lich's",
    "Mad Lord's",
    "Magister's",
    "Marchioness's",
    "Martinet's",
    "Master's",
    "Matatl's",
    "Merciless",
    "Nautilus's",
    "of Abjuration",
    "of Bameth",
    "of Coercion",
    "of Ephij",
    "of Ferocity",
    "of Grandmastery",
    "of Guatelitzi",
    "of Haast",
    "of Lioneye",
    "of Prestidigitation",
    "of Puhuarte",
    "of Puncturing",
    "of Tacati",
    "of the Blur",
    "of the Deadeye",
    "of the Deathless",
    "of the Essence",
    "of the Fanatical",
    "of the Genius",
    "of the Gods",
    "of the Godslayer",
    "of the Lightning Rod",
    "of the Lightning",
    "of the Marksman",
    "of the Multiverse",
    "of the Polymath",
    "of the Rainbow",
    "of the Ranger",
    "of the Span",
    "of the Tempest",
    "of the Underground",
    "of the Volcano",
    "of the Wind",
    "of the Zealous",
    "of Tzteosh",
    "of Vivification",
    "Prior's",
    "Provocateur's",
    "Queen's",
    "Ram's",
    "Resplendent",
    "Rimedweller's",
    "Rune",
    "Saintly",
    "Spirit's",
    "Splintermind's",
    "Stormbrewer's",
    "Tacati's",
    "Tacati",
    "Taskmaster's",
    "Tecton's",
    "Topotante's",
    "Tul's",
    "Tyrannical",
    "Unassailable",
    "Victor's",
    "Vile",
    "Xopec's",
    "Xoph's",
];
