#########################################
# The main configuration for the filter #
#########################################

[env]
# The folder destination and name of the filter, can be relative or absolute
destination = "./FilterMaker.filter"

# A list of items that get the highest visual importance (S-Tier)
schwings = """
    Albino Rhoa Feather
    Awakener's Orb
    Blessing of Chayula
    Blessing of Esh
    Blessing of Tul
    Blessing of Uul-Netol
    Blessing of Xoph
    Crusader's Exalted Orb
    Divine Orb
    Elder's Exalted Orb
    Eternal Orb
    Exceptional Eldritch Ember
    Exceptional Eldritch Ichor
    Fracturing Orb
    Fracturing Shard
    Hinekora's Lock
    Hunter's Exalted Orb
    Mirror of Kalandra
    Mirror Shard
    Orb of Conflict
    Orb of Dominance
    Orb of Intention
    Orb of Remembrance
    Orb of Unravelling
    Redeemer's Exalted Orb
    Reflecting Mist
    Sacred Crystallised Lifeforce
    Shaper's Exalted Orb
    Tailoring Orb
    Tainted Divine Teardrop
    Tainted Exalted Orb
    Tempering Orb
    Valdo's Puzzle Box
    Veiled Exalted Orb
    Warlord's Exalted Orb
    Faceted Fossil
    Fractured Fossil
    Glyphic Fossil
    Hollow Fossil
    Assassin's Gift
    Auspicious Ambitions
    Beauty Through Death
    Broken Promises
    Brother's Gift
    Brother's Stash
    Choking Guilt
    Damnation
    Darker Half
    Desecrated Virtue
    Divine Beauty
    Divine Justice
    Duality
    Father's Love
    Fire Of Unknown Origin
    History
    House of Mirrors
    I See Brothers
    Imperfect Memories
    Last Stand
    Lonely Warrior
    Love Through Ice
    Luminous Trove
    Magnum Opus
    Matryoshka
    Remembrance
    Seven Years Bad Luck
    Squandered Prosperity
    Succor of the Sinless
    Temperance
    The Apothecary
    The Artist
    The Cheater
    The Damned
    The Demon
    The Destination
    The Doctor
    The Dragon's Heart
    The Endless Darkness
    The Enlightened
    The Fiend
    The Greatest Intentions
    The Gulf
    The Immortal
    The Insane Cat
    The Last Supper
    The Leviathan
    The Long Con
    The Mayor
    The Price of Devotion
    The Progeny of Lunaris
    The Sacrifice
    The Samurai's Eye
    The Sephirot
    The Shieldbearer
    The Soul
    The Vast
    The World Eater
    Tranquillity
    Unrequited Love
    Wealth and Power
    Winter's Embrace
    Runegraft of Gemcraft
    Runegraft of the Angler
    Allflame Ember of the Ethereal
    Allflame Ember of the Gilded
    Ambush Scarab of Containment
    Horned Scarab of Awakening
    Horned Scarab of Preservation
    Ultimatum Scarab of Catalysing
    Archive Reliquary Key
    Cosmic Reliquary Key
    Decaying Reliquary Key
    Forgotten Reliquary Key
    Oubliette Reliquary Key
    Shiny Reliquary Key
    Visceral Reliquary Key
    Voidborn Reliquary Key
    Golden Oil
    Prismatic Oil
    Tainted Oil
    Reflective Oil
"""

# A list of items that get somewhat high visual importance (A-Tier)
dings = """
    Deafening Essence of Greed
    Deafening Essence of Contempt
    Deafening Essence of Hatred
    Deafening Essence of Woe
    Deafening Essence of Fear
    Deafening Essence of Anger
    Deafening Essence of Torment
    Deafening Essence of Sorrow
    Deafening Essence of Rage
    Deafening Essence of Suffering
    Deafening Essence of Wrath
    Deafening Essence of Doubt
    Deafening Essence of Loathing
    Deafening Essence of Zeal
    Deafening Essence of Anguish
    Deafening Essence of Spite
    Deafening Essence of Scorn
    Deafening Essence of Envy
    Deafening Essence of Misery
    Deafening Essence of Dread
    Essence of Delirium
    Essence of Horror
    Essence of Hysteria
    Essence of Insanity
    Prime Chaotic Resonator
    Sanctified Fossil
    A Familiar Call
    A Fate Worse Than Death
    A Modest Request
    Alluring Bounty
    Ambitious Obsession
    Anarchy's Price
    Azyran's Reward
    Burning Blood
    Chasing Risk
    Deadly Joy
    Doryani's Epiphany
    Dying Light
    Fateful Meeting
    Friendship
    Further Invention
    Gemcutter's Mercy
    Home
    Judging Voices
    Monochrome
    Pride of the First Ones
    Silence and Frost
    Terrible Secret of Space
    The Academic
    The Aspirant
    The Astromancer
    The Bargain
    The Cartographer
    The Chosen
    The Deep Ones
    The Emptiness
    The Eternal War
    The Eye of Terror
    The Fishmonger
    The Fortunate
    The Garish Power
    The Last One Standing
    The Nurse
    The One That Got Away
    The Price of Loyalty
    The Queen
    The Rabbit's Foot
    The Scout
    The Wedding Gift
    Who Asked
    Crescent Splinter
    Eldritch Chaos Orb
    Eldritch Exalted Orb
    Eldritch Orb of Annulment
    Exalted Orb
    Maven's Chisel of Avarice
    Maven's Chisel of Divination
    Maven's Chisel of Proliferation
    Maven's Chisel of Scarabs
    Prismatic Catalyst
    Sacred Orb
    Tempering Catalyst
    Veiled Chaos Orb
    Allflame Ember of Kulemak
    Allflame Ember of Propagation
    Allflame Ember of Resplendence
    Blight Scarab of Blooming
    Blight Scarab of Invigoration
    Cartography Scarab of Risk
    Divination Scarab of Pilfering
    Domination Scarab of Terrors
    Essence Scarab of Calcification
    Harvest Scarab of Cornucopia
    Horned Scarab of Bloodlines
    Horned Scarab of Pandemonium
    Incursion Scarab of Timelines
    Cosmic Fragment
    Decaying Fragment
    Awakening Fragment
    Synthesising Fragment
    Reality Fragment
    Devouring Fragment
    Blazing Fragment
    Silver Oil
    Echo of Loneliness
    Echo of Reverence
    Echo of Trauma
"""

# A list of items that get some visual importance (B-Tier)
pings = """
    Potent Chaotic Resonator
    Powerful Chaotic Resonator
    Primitive Chaotic Resonator
    Aberrant Fossil
    Aetheric Fossil
    Bloodstained Fossil
    Bound Fossil
    Corroded Fossil
    Deft Fossil
    Dense Fossil
    Frigid Fossil
    Fundamental Fossil
    Gilded Fossil
    Jagged Fossil
    Lucent Fossil
    Metallic Fossil
    Opulent Fossil
    Prismatic Fossil
    Pristine Fossil
    Scorched Fossil
    Serrated Fossil
    Shuddering Fossil
    Tangled Fossil
    Remnant of Corruption
    Shrieking Essence of Greed
    Shrieking Essence of Contempt
    Shrieking Essence of Hatred
    Shrieking Essence of Woe
    Shrieking Essence of Fear
    Shrieking Essence of Anger
    Shrieking Essence of Torment
    Shrieking Essence of Sorrow
    Shrieking Essence of Rage
    Shrieking Essence of Suffering
    Shrieking Essence of Wrath
    Shrieking Essence of Doubt
    Shrieking Essence of Loathing
    Shrieking Essence of Zeal
    Shrieking Essence of Anguish
    Shrieking Essence of Spite
    Shrieking Essence of Scorn
    Shrieking Essence of Envy
    Shrieking Essence of Misery
    Shrieking Essence of Dread
    Screaming Essence of Greed
    Screaming Essence of Contempt
    Screaming Essence of Hatred
    Screaming Essence of Woe
    Screaming Essence of Fear
    Screaming Essence of Anger
    Screaming Essence of Torment
    Screaming Essence of Sorrow
    Screaming Essence of Rage
    Screaming Essence of Suffering
    Screaming Essence of Wrath
    Screaming Essence of Doubt
    Screaming Essence of Loathing
    Screaming Essence of Zeal
    Screaming Essence of Anguish
    Screaming Essence of Spite
    Screaming Essence of Scorn
    Screaming Essence of Envy
    Screaming Essence of Misery
    Screaming Essence of Dread
    Astragali
    Burial Medallion
    Chaos Orb
    Exalted Shard
    Gemcutter's Prism
    Grand Eldritch Ichor
    Grand Eldritch Ember
    Greater Eldritch Ichor
    Greater Eldritch Ember
    Harbinger's Orb
    Imbued Catalyst
    Intrinsic Catalyst
    Noxious Catalyst
    Tainted Catalyst
    Turbulent Catalyst
    Unstable Catalyst
    Fertile Catalyst
    Abrasive Catalyst
    Accelerating Catalyst
    Orb of Annulment
    Primal Crystallised Lifeforce
    Ritual Splinter
    Scrap Metal
    Stacked Deck
    Tainted Armourer's Scrap
    Tainted Blacksmith's Whetstone
    Tainted Chromatic Orb
    Tainted Jeweller's Orb
    Tainted Chaos Orb
    Tainted Mythic Orb
    Tainted Orb of Fusing
    Veiled Scarab
    Vivid Crystallised Lifeforce
    Wild Crystallised Lifeforce
    Ancient Orb
    Exotic Coinage
    Ritual Vessel
    Ancient Shard
    Annulment Shard
    Bestiary Orb
    Cartographer's Chisel
    Enkindling Orb
    Facetor's Lens
    Glassblower's Bauble
    Orb of Horizons
    Orb of Regret
    Orb of Scouring
    Orb of Unmaking
    Orb of Alteration
    Orb of Chance
    Chromatic Orb
    Orb of Fusing
    Regal Orb
    Vaal Orb
    Misery in Darkness
    Rogue's Marker
"""

# A list of unique items that recieve the highest visual importance (Tier 0)
uniques = """
    Astrolabe Amulet
    Cabalist Regalia
    Candlestick Relic
    Champion Kite Shield
    Crusader Boots
    Dusk Blade
    Engraved Greatsword
    Fluted Bascinet
    Foul Staff
    Ghastly Eye Jewel
    Girded Tower Shield
    Gold Flask
    Golden Buckler
    Greatwolf Talisman
    Imperial Maul
    Karui Maul
    Lacewood Spirit Shield
    Martyr Gloves
    Papyrus Relic
    Prismatic Jewel
    Processional Relic
    Raven Mask
    Ring
    Riveted Boots
    Ruby Flask
    Runic Crown
    Runic Helm
    Runic Sollerets
    Savant's Robe
    Siege Axe
    Siege Helmet
    Slaughter Knife
    Unset Amulet
    Vaal Rapier
    Vermillion Ring
    Void Axe
"""

# A list of unique items that get some visual importance
dust_uniques = """
    Opal Ring
    Heavy Belt
    Leather Belt
    Midnight Blade
    Triumphant Lamellar
    Callous Mask
    Bone Helmet
"""

# A list of unique items that will be specifically hidden by the filter
hide_uniques = """
    Iron Ring
    Coral Ring
    Paua Ring
    Sapphire Ring
    Topaz Ring
    Ruby Ring
    Gold Ring
    Two-Stone Ring
    Diamond Ring
    Moonstone Ring
    Prismatic Ring
"""

# All maps at or above this number will be shown by the filter
map_tier = "16"

# When set to "true", progressively larger gold piles based on amount will be shown by the filter
show_gold = "true"

# When set to "true", all fractured bases will be shown by the filter
show_fractured_bases = "true"

# When set to "true", all influenced bases will be shown by the filter
show_influenced_bases = "true"

# When set to "true", all synthesized bases will be shown by the filter
show_synthesized_bases = "true"

# When set to "true", all bases with six links will be shown by the filter
show_six_link_bases = "false"