[configs]
destination = "./FilterMaker.filter"
sounds = [ "gong", "hollow_drum", "voice_drum", "voice_whoosh", "low_whoosh", "glitter", "tonal_pulse", "mechanical_pulse", "slow_pulse" ]
icons = [ "circle", "diamond", "hexagon", "square", "star", "triangle", "cross", "moon", "raindrop", "kite", "pentagon", "upsidedown_house" ]
palette = [
    # regular
    { name = "none", color = { r = 0, g = 0, b = 0, a = 0 }},
    { name = "white", color = { r = 200, g = 200, b = 200, a = 255 }},
    { name = "black", color = { r = 42, g = 42, b = 42, a = 255 }},
    { name = "red", color = { r = 191, g = 0, b = 0, a = 255 }},
    { name = "pink", color = { r = 254, g = 128, b = 128, a = 255 }},
    { name = "orange", color = { r = 175, g = 96, b = 37, a = 255 }},
    { name = "gold", color = { r = 187, g = 165, b = 61, a = 255 }},
    { name = "yellow", color = { r = 225, g = 225, b = 119, a = 255 }},
    { name = "green", color = { r = 27, g = 119, b = 65, a = 255 }},
    { name = "teal", color = { r = 7, g = 122, b = 115, a = 255 }},
    { name = "neon_teal", color = { r = 0, g = 202, b = 177, a = 255 }},    
    { name = "blue", color = { r = 136, g = 136, b = 255, a = 255 }},
    { name = "purple", color = { r = 192, g = 118, b = 223, a = 255 }},
    { name = "beige", color = { r = 200, g = 200, b = 175, a = 255 }},
    { name = "salmon_red", color = { r = 255, g = 85, b = 85, a = 255 }},
    { name = "grey", color = {r = 162, g = 160, b = 159, a = 255 }},
    { name = "vibrant_blue", color = { r = 45, g = 45, b = 215, a = 255 }},
    { name = "orange_red", color = { r = 255, g = 112, b = 59, a = 255 }},
    { name = "off_white", color = {r = 212, g = 210, b = 209, a = 255 }},
    { name = "abyssal_green", color = {r = 76, g = 187, b = 23, a = 255 }},
    { name = "washed_out_red", color = {r = 125, g = 50, b = 50, a = 255 }},
    { name = "washed_out_blue", color = {r = 50, g = 50, b = 125, a = 255 }},
    { name = "washed_out_purple", color = {r = 105, g = 30, b = 125, a = 255 }},
    # darks
    { name = "dark_blue", color = { r = 41, g = 128, b = 185, a = 255 }},
    { name = "dark_orange", color = { r = 145, g = 66, b = 7, a = 255 }},
    { name = "dark_purple", color = { r = 142, g = 68, b = 173, a = 255 }},
    { name = "dark_red", color = { r = 71, g = 0, b = 0, a = 255 }},
    # faded
    { name = "faded_white", color = { r = 200, g = 200, b = 200, a = 205 }},
    { name = "faded_black", color = { r = 42, g = 42, b = 42, a = 170 }},
    { name = "faded_red", color = { r = 191, g = 0, b = 0, a = 105 }},
    { name = "faded_dark_orange", color = { r = 145, g = 66, b = 7, a = 190 }},
    { name = "faded_beige", color = { r = 200, g = 200, b = 175, a = 190 }},
    { name = "faded_dark_blue", color = { r = 41, g = 128, b = 185, a = 190 }},
    { name = "faded_dark_purple", color = {r = 105, g = 30, b = 125, a = 120 }},
    { name = "faded_dark_red", color = { r = 61, g = 0, b = 0, a = 155 }},
]
styles = [
    { name = "Default (base style)", font = "white", background = "faded_black", size = 22 },
    { name = "Magic (base style)", rarity = "Magic", font = "blue", size = 28 },
    { name = "Rare (base style)", rarity = "Rare", font = "yellow", size = 28 },
    { name = "Unique (base style)", rarity = "Unique", font = "white", background = "orange", size = 28 },
    { name = "Unique Corrupted (base style)", corrupted_mods = 1, rarity = "Unique", font = "orange", background = "orange_red", outline = "dark_red", size = 28 },
    { name = "Corrupted mods (base style)", corrupted_mods = 1, rarity = "none", background = "faded_dark_red", outline = "dark_red" },
    { name = "Currency (base style)", classes = [ "Currency" ], rarity = "none", font = "off_white", background = "dark_purple", size = 28 },
    { name = "Gold (base style)", items = [ "gold" ], rarity = "none", font = "gold", background = "faded_black", size = 20 },
    { name = "Portal Scrolls (base style)", items = [ "portal scroll" ], font = "washed_out_blue", background = "grey", outline = "washed_out_blue", size = 20 },
    { name = "Scroll of Wisdom (base style)", items = [ "scroll of wisdom" ], font = "washed_out_red", background = "grey", outline = "washed_out_red", size = 20 },
    { name = "Waystones (base style)", classes = [ "Waystone" ], rarity = "none", background = "black", size = 20 },
    { name = "Uncut Gems (base style)", classes = [ "Uncut Skill Gems", "Uncut Spirit Gems", "Uncut Support Gems" ], font = "teal", background = "white", outline = "teal", size = 28, strict = false },
    { name = "Fragments (base style)", classes = [ "Map Fragments" ], font = "white", background = "red", outline = "white", size = 24 },
    { name = "Flasks (base style)", items = [ "flask" ], font = "purple", background = "faded_black", strict = false, size = 20 },
    { name = "Fractured (base style)", is_fractured = true, rarity = "none", font = "white", background = "teal", outline = "white", size = 26 },
    { name = "Perfect Essences (base style)", items = [ "perfect essence of" ], font = "dark_blue", background = "off_white", size = 34, strict = false},
    { name = "Essences (base style)", items = [ "essence of" ], font = "dark_blue", background = "off_white", size = 26, strict = false},
    { name = "Runes (base style)", classes = [ "Socketable" ], font = "purple", background = "white", outline = "purple", size = 28 },
    { name = "Omens (base style)", classes = [ "Omen" ], font = "neon_teal", background = "faded_black", outline = "white", size = 32 },
    { name = "Tablets (base style)", classes = [ "Tablet" ], font = "white", background = "faded_dark_blue", outline = "white", size = 28 },
    { name = "Trials (base style)", classes = [ "Inscribed Ultimatum", "Trial Coins" ], font = "black", background = "off_white", outline = "black", size = 28 },
    { name = "Logbooks (base style)", classes = [ "Expedition Logbooks" ], font = "dark_blue", background = "off_white", outline = "dark_blue", size = 34 },
    { name = "Jewels", classes = [ "Jewels" ], background = "faded_purple", outline = "purple", size = 26 },
    { name = "Abyssal (base style)", classes = [ "Stackable Currency", "Omen" ], items = [  "Preserved", "Ancient", "Gnawed", "Abyssal Echoes", "Sovereign", "Liege", "Blackblooded", "Putrefaction", "Light", "Sinistral Necromancy", "Dextral Necromancy" ], rarity = "none", font = "abyssal_green", background = "black", outline = "abyssal_green", size = 32, strict = false },
    { name = "Frags (base style)", classes = [ "Pinnacle Keys" ], font = "dark_purple", background = "off_white", outline = "dark_purple", size = 38 },
]


[[filters]]
name = "Ultra Valuable Items"
items = [ "Albino Rhoa Feather", "Ancient Collarbone", "Ancient Jawbone", "Ancient Rib", "Divine Orb", "Hinekora's Lock", "Mirror of Kalandra", "Perfect Chaos Orb", "Perfect Exalted Orb", "Amanamu's Gaze", "Countess Seske's Rune of Archery", "Farrul's Rune of the Chase", "Fox Talisman", "Hedgewitch Assandra's Rune of Wisdom", "Rabbit Talisman", "Saqawal's Rune of the Sky", "Soul Core of Jiquani", "Talisman of Ralakesh", "Talisman of Sirrius", "Thane Leld's Rune of Spring", "Arjun's Medal", "Atalui's Bloodletting", "Dialla's Desire", "Esh's Radiance", "Rakiata's Flow", "Ratha's Assault", "Uhtred's Augury", "Uhtred's Omen", "Uul-Netol's Embrace", "essence of Horror", "essence of hysteria" ]
theme = { font = "red", background = "white", outline = "red" }
size = 48
sound = { sound_type = "glitter", volume = "loud" }
icon = { icon_type = "star", color = "red", size = "large" }
beam = "red"

[[filters]]
name = "Very Valuable Items"
items = [ "Fracturing Orb", "Orb of Annulment", "Perfect Regal Orb", "Perfect Jeweller's Orb", "Preserved Collarbone", "Atmohua's Soul Core of Retreat", "Saqawal's Rune of Memory", "Soul Core of Azcapa", "Soul Core of Tacati", "Tecrod's Gaze", "Thane Girt's Rune of Wildness", "The Greatwolf's Rune of Claws", "The Greatwolf's Rune of Willpower", "Amanamu's Tithe", "Arbiter's Ignition", "Brutus' Brain", "Garukhan's Resolve", "Ixchel's Torment", "Kalisa's Crescendo", "Romira's Requital", "Tul's Stillness", "Uhtred's Exodus", "Rigwald's Ferocity" ]
theme = { font = "dark_orange", background = "white", outline = "dark_orange" }
size = 38
sound = { sound_type = "low_whoosh", volume = "normal" }
icon = { icon_type = "circle", color = "orange", size = "medium" }
beam = "orange"

[[filters]]
name = "Valuable Items"
items = [ "Chaos Orb", "Exalted Orb", "Exotic Coinage", "Greater Chaos Orb", "Greater Exalted Orb", "Greater Regal Orb", "Orb of Chance", "Preserved Cranium", "Courtesan Mannan's Rune of Cruelty", "Kurgal's Gaze", "Opiloti's Soul Core of Assault", "Primate Talisman", "Soul Core of Citaqualotl", "Soul Core of Quipolatl", "Talisman of Egrin", "Talisman of Grold", "Thane Grannell's Rune of Mastery", "Thane Myrk's Rune of Summer", "Ulaman's Gaze", "Xopec's Soul Core of Power", "Ahn's Citadel", "Ailith's Chimes", "Arakaali's Lust", "Atziri's Allure", "Daresso's Passion", "Doedre's Undoing", "Einhar's Beastrite", "Kaom's Madness", "Kulemak's Dominion", "Kurgal's Leash", "Paquate's Pact", "Piety's Mercy", "Sione's Temper", "Tacati's Ire", "Tawhoa's Tending", "Tecrod's Revenge", "Uruk's Smelting", "Varashta's Blessing", "Vilenta's Propulsion", "Xoph's Pyre", "Zarokh's Refrain" ]
size = 32
sound = { sound_type = "hollow_drum", volume = "normal" }
icon = { icon_type = "circle", color = "purple", size = "small" }

[[filters]]
name = "Reliquary Keys"
items = [ "Reliquary Key" ]
theme = { font = "white", background = "dark_blue", outline = "white" }
size = 38
sound = { sound_type = "mechanical_pulse", volume = "normal" }
icon = { icon_type = "raindrop", color = "blue", size = "medium" }
strict = false

[[filters]]
name = "Tier 0 Uniques"
items = [ "Armoured Cap", "Blacksteel Tower Shield", "Conqueror Plate", "Desolate Crossbow", "Embroidered Gloves", "Emerald", "Fine Bracers", "Golden Charm", "Incense Relic", "Intricate Crest Shield", "Lattice Sandals", "Ornate Gauntlets", "Primed Quiver", "Ring", "Sacred Focus", "Sapphire", "Silver Charm", "Thawing Charm", "Ultimate Life Flask", "Utility Wraps" ]
rarity = "Unique"
theme = { font = "red", background = "white", outline = "red" }
size = 48
sound = { sound_type = "glitter", volume = "loud" }
icon = { icon_type = "star", color = "red", size = "large" }
beam = "red"

[[filters]]
name = "Good Uniques"
items = [ "Breach Precursor Tablet", "Chain Tiara", "Delirium Precursor Tablet", "Diamond", "Expedition Precursor Tablet", "Heroic Armour", "Moulded Mitts", "Overseer Precursor Tablet", "Precursor Tablet", "Ritual Precursor Tablet", "Ruby", "Spiral Wraps", "Stone Charm", "Time-Lost Diamond", "Timeless Jewel", "Unset Ring", "Vase Relic", "Viper Cap", "Abyssal Signet", "Grand Regalia", "Heavy Belt", "Jade Amulet", "Pearl Ring", "Ravenous Staff", "Shrine Sceptre", "Amethyst Ring", "Bloodstone Amulet", "Crude Bow", "Lazuli Ring", "Stellar Amulet" ]
rarity = "Unique"
size = 42
sound = { sound_type = "voice_drum", volume = "normal" }
icon = { icon_type = "star", color = "orange", size = "medium" }
beam = "orange"

[[filters]]
name = "Corrupted items"
corrupted_mods = 1

[[filters]]
name = "Gold (large pile)"
items = [ "gold" ]
theme = { font = "gold", background = "faded_black", outline = "gold" }
stack_size = 500
size = 40
icon = { icon_type = "star", color = "yellow", size = "medium" }
beam = "yellow"

[[filters]]
name = "Gold (medium pile)"
items = [ "gold" ]
theme = { font = "gold", background = "faded_black", outline = "gold" }
stack_size = 150
size = 28
icon = { icon_type = "star", color = "yellow", size = "small" }

[[filters]]
name = "Gold (small pile)"
items = [ "gold" ]
size = 24
icon = { icon_type = "star", color = "yellow", size = "small" }

[[filters]]
name = "Perfect Quality items"
theme = { outline = "off_white" }
size = 38
quality = 27
beam = "white"

[[filters]]
name = "Over-Qualitied Items"
theme = { outline = "off_white" }
size = 34
quality = 20
beam = "white"

[[filters]]
name = "High Quality items"
theme = { outline = "off_white" }
size = 32
quality = 10
beam = "white"

[[filters]]
name = "Warrior bases"
size = 38
item_level = 74
items = [ "Warlord Cuirass", "Tasalian Greaves", "Massive Mitts", "Imperial Greathelm", "Massive Greathammer", "Tawhoan Greatclub", "Tawhoan Tower Shield" ]
icon = { icon_type = "raindrop", color = "white", size = "medium" }
beam = "green"

[[filters]]
name = "Ranger bases"
size = 38
item_level = 74
items = [ "Quickslip Shoes", "Daggerfoot Shoes", "Secured Wraps", "Grinning Mask", "Visceral Quiver", "Primed Quiver", "Gemini Bow", "Obliterator Bow", "Warmonger Bow", "slipstrike vest" ]
icon = { icon_type = "raindrop", color = "white", size = "medium" }
beam = "green"

[[filters]]
name = "Energy Shield bases"
size = 38
item_level = 74
items = [ "Vile Robe", "Sekhema Sandals", "Sirenscale Gloves", "Ancestral Tiara" ]
icon = { icon_type = "raindrop", color = "white", size = "medium" }
beam = "green"

[[filters]]
name = "Valuable bases"
size = 42
item_level = 81
theme = { font = "white", background = "green", outline = "white" }
items = [ "Attuned Wand", "Solar Amulet" ]
sound = { sound_type = "low_whoosh", volume = "normal" }
icon = { icon_type = "raindrop", color = "green", size = "medium" }
beam = "green"

[[filters]]
name = "Gamble bases"
theme = { font = "black", background = "gold", outline = "black" }
rarity = "Normal"
size = 42
items = [ "Heavy Belt", "Silver Charm", "Stellar Amulet", "Sacred Focus" ]
sound = { sound_type = "low_whoosh", volume = "normal" }
icon = { icon_type = "diamond", color = "yellow", size = "large" }
beam = "yellow"

[[filters]]
name = "Tier 5 Rares"
rarity = "Rare"
size = 42
item_tier = 5
sound = { sound_type = "voice_drum", volume = "normal" }
icon = { icon_type = "circle", color = "yellow", size = "medium" }
beam = "yellow"

[[filters]]
name = "Tier 5 Items"
item_tier = 5
sound = { sound_type = "hollow_drum", volume = "normal" }
icon = { icon_type = "circle", color = "blue", size = "small" }
beam = "blue"

[[filters]]
name = "Tier 4 Items"
item_tier = 4

[[filters]]
name = "Fractured Items"
is_fractured = true

[[filters]]
name = "Unique Items"
rarity = "Unique"

[[filters]]
name = "jewellery"
classes = [ "Rings", "Amulets", "Belts" ]

[[filters]]
name = "Boss Frags"
classes = [ "Pinnacle Keys" ]
sound = { sound_type = "low_whoosh", volume = "normal" }
icon = { icon_type = "star", color = "purple", size = "medium" }

[[filters]]
name = "Hidden Currency"
items = [ "Lesser Jeweller's Orb" ]
hide = true

[[filters]]
name = "All other shown classes"
classes = [ "Currency", "Omen", "Socketable", "Waystone", "Tablet", "Uncut Skill Gems", "Uncut Spirit Gems", "Uncut Support Gems", "Map Fragments", "Expedition Logbooks", "Inscribed Ultimatum", "Trial Coins", "Jewels" ]

[[filters]]
name = "Hide all"
hide = true